services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: dbuser
      POSTGRES_DB: dbname
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/dados_ans:/dados_ans  # Monta database/dados_ans no contêiner
    networks:
      - pg-network

volumes:
  pgdata:

networks:
  pg-network:
    driver: bridge